version: "3"

services: 
  app:
    build:
      context: .
    # Maps ports and volumes from project to docker image
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"